### PR TITLE
Issue-3 update dependencies

### PR DESCRIPTION
**Pull request by Ghazgkull**
Addresses #3 

This PR updates the dependencies of the @adnanrahic/node-gcstats module to the latest. Most importantly, it updates this package to stop using the deprecated `node-pre-gyp` package in favor of the supported `@mapbox/node-pre-gyp` module. See the deprecation notice on the old module here: https://www.npmjs.com/package/node-pre-gyp

This PR also includes updates to keep the unit tests working with the latest mocha version. I renamed the `tests` folder to `test` because that's what the newest Mocha expects. And I updated the test command to pass the `--expose-gc` command to node directly, since Mocha no longer supports passing the flag through.

@adnanrahic Please take a look.

### CODE REVIEW

**Comment by Jarco-dev** [comment]
Waiting on this, hope it can get merged soon.
(Due to the audit failing i can't install on linux atm)

**Review by adnanrahic — APPROVED** [review]

**Comment by baconandon** [comment]
Sorry to be the bearer of bad news, but... even though the [`node-pre-gyp` dependency](https://github.com/adnanrahic/node-gcstats/pull/4/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L23)  was removed it is [still bundled](https://github.com/adnanrahic/node-gcstats/pull/4/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R33) 

Which means
1. `npm i @sematext/gc-stats` installs `node-pre-gyp` as well as `@mapbox/node-pre-gyp`
2. `npm audit` => 😢 (because of `tar` dependencies from `node-pre-gyp`)

FWIW `npm ls node-pre-gyp` after the install shows 
```
┬ @sematext/gc-stats@1.5.4
  └── node-pre-gyp@0.15.0
```

HTH

**Comment by Ghazgkull** [comment]
@baconandon At this point, you know as much about this repo as I do. :-) I see that @adnanrahic created Issue #1 a while back to remove the bundled dependency, but it seems like that never happened. Is it as simple as just removing the bundled dependency lines from the package.json manifest or are there other things to consider?

**Comment by Ghazgkull** [comment]
@baconandon @adnanrahic Actually, I decided to just give it a shot. I fixed everything up and submitted a PR: https://github.com/adnanrahic/node-gcstats/pull/6

**Pull request merged**
