### PR TITLE
Issue-1 remove bundled node-pre-gyp

### PR DESCRIPTION
**Pull request by Ghazgkull**
Signed-off-by: Jared Burns <jared.burns@nike.com>

Fixes Issue #1 

This PR removes the bundled `node-pre-gyp` package, so that the `@mapbox/node-pre-gyp` package gets used instead. It also updates all dependencies to latest and fixes up the package.json scripts so that they all work.

### CODE REVIEW

**Comment by Ghazgkull** [comment]
@adnanrahic Can you please have a look at this PR? This completes the cleanup of any references to the deprecated `node-pre-gyp` package.

**Comment by nyablonskyi360** [comment]
Hey @adnanrahic, thank you for supporting this lib, and thank you @Ghazgkull for your PR.

@adnanrahic Could you please review this?

**Review by adnanrahic — APPROVED** [review]
Thanks for the contribution! This looks great. :smile:

**Comment by nyablonskyi360** [comment]
Thanks @adnanrahic! Looking forward to the new release :)

**Comment by adnanrahic** [comment]
I've released a new version. It'll be available on NPM momentarily. :smile: 
Thanks for the help @Ghazgkull! :pray:

**Pull request merged**
